# Generated by Django 4.2.20 on 2025-04-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='createaccount',
            fields=[
                ('StudentId', models.IntegerField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=25, unique=True)),
                ('MobileNo', models.CharField(max_length=10, unique=True)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
            ],
        ),
    ]
