# Generated by Django 4.2.20 on 2025-04-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Institution', models.CharField(max_length=25, unique=True)),
                ('Course', models.CharField(choices=[('School', 'School'), ('UG Degree', 'UG Degree'), ('PG Degree', 'PG Degree'), ('Others', 'Others')], max_length=15)),
                ('Year', models.DateField()),
            ],
        ),
    ]
