# Generated by Django 4.2.20 on 2025-04-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='Institution',
            field=models.CharField(max_length=25),
        ),
    ]
