# Generated by Django 4.2.20 on 2025-04-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_education_institution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='createaccount',
        ),
    ]
