# Generated by Django 4.2.20 on 2025-04-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_createaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='StudentName',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
